// Curated suggestion set: healthy, high-protein, low-sugar, freeze-well recipes.
// 10 breakfast / 10 lunch / 10 dinner. Verified from source sites (macros are per-serving as published).
// Shown in the "Suggested" tab for review; "Save to Library" pushes into the family recipe vault.

const ing = (name, aisle = "Other") => ({
  name, qty: 1, unit: "", pK: 0, pW: 0, pA: 0, pS: 0, pC: 0, onSale: false, saleDesc: "", aisle,
});

const R = (o) => ({
  id: "", category: "Chicken", mealType: "Dinner",
  prepTime: 15, cookTime: 30, servings: 4, rating: 5,
  favorite: false, noRecipeNeeded: false,
  image: "", source: "suggested", sourceUrl: "", videoUrl: "", notes: "", tags: ["Healthy", "Meal Prep"],
  ingredients: [], instructions: "", cookLog: [],
  macros: { calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, sodium: 0 },
  ...o,
});

export const SUGGESTED_RECIPES = [
  // ============================== BREAKFAST ==============================
  R({
    id: "sg-b1", title: "High Protein Egg White Muffins with Turkey Bacon",
    category: "Breakfast", mealType: "Breakfast", prepTime: 15, cookTime: 35, servings: 6,
    source: "Skinnytaste", sourceUrl: "https://www.skinnytaste.com/egg-white-muffins/",
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/02/Egg-White-Muffins-with-Turkey-Bacon-Cottage-Cheese-and-Veggies-8.jpg",
    tags: ["Healthy", "Meal Prep", "Kid Friendly"],
    notes: "Serving = 2 muffins. Freezes well — reheat from frozen ~1 min in microwave. Fridge up to 4 days. Veggies are hidden in the egg base.",
    macros: { calories: 144, protein: 20, carbs: 4.5, fat: 4.5, fiber: 1, sugar: 2, sodium: 502 },
    ingredients: [
      ing("1/2 tbsp extra virgin olive oil"), ing("16 oz carton egg whites"),
      ing("5.3 oz container 2% cottage cheese (just over 1/2 cup)"),
      ing("1/2 tsp garlic powder"), ing("1/4 tsp seasoning salt (like adobo)"),
      ing("1/4 cup chopped shallots or red onion"), ing("1/4 cup chopped scallions"),
      ing("1 medium orange or red bell pepper, chopped"),
      ing("1/2 cup chopped steamed broccoli (fresh or frozen)"),
      ing("6 slices uncured turkey bacon, cut in half"),
      ing("1/4 cup sharp shredded cheddar cheese"), ing("Olive oil spray"),
    ],
    instructions: "1. Preheat oven to 350°F. Spray a 12-cup nonstick muffin tin generously with oil.\n2. Sauté shallots, scallions and bell pepper in oil over medium-low heat 5-6 min until tender.\n3. Add broccoli and cook 1 more minute.\n4. In a large bowl combine egg whites, cottage cheese, garlic powder and seasoning salt.\n5. Mix in the cooked vegetables.\n6. Line each muffin cup with a half slice of turkey bacon around the edges. Pour egg mixture into each (~1/3 cup).\n7. Top with shredded cheese.\n8. Bake ~25 min until set.",
  }),
  R({
    id: "sg-b2", title: "Broccoli and Cheese Egg Muffins",
    category: "Breakfast", mealType: "Breakfast", prepTime: 5, cookTime: 30, servings: 4,
    source: "Skinnytaste", sourceUrl: "https://www.skinnytaste.com/broccoli-and-cheese-mini-egg-omelets-2/",
    image: "https://www.skinnytaste.com/wp-content/uploads/2013/04/Broccoli-and-Cheese-Egg-Muffins-6.jpg",
    tags: ["Healthy", "Meal Prep", "Kid Friendly"],
    notes: "Serving = 2 muffins. Hidden veggie (broccoli). Freeze and reheat; fridge up to 5 days.",
    macros: { calories: 167, protein: 18, carbs: 5, fat: 8.5, fiber: 2.5, sugar: 1, sodium: 317 },
    ingredients: [
      ing("4 cups broccoli florets"), ing("4 large whole eggs"), ing("1 cup egg whites"),
      ing("1/4 cup reduced fat shredded cheddar cheese"),
      ing("1/4 cup Pecorino Romano or Parmesan cheese, grated"),
      ing("1 tsp olive oil"), ing("Salt and fresh pepper to taste"), ing("Olive oil spray"),
    ],
    instructions: "1. Preheat oven to 350°F.\n2. Steam broccoli with a little water 3-5 min.\n3. Crumble broccoli into smaller pieces; mix with olive oil, salt and pepper.\n4. Spray a nonstick muffin tin; spoon broccoli evenly into 9 cups.\n5. Beat egg whites, eggs, grated cheese, salt and pepper.\n6. Pour egg mixture over broccoli until just over 3/4 full.\n7. Top with cheddar and bake ~20 min until set.\n8. Serve or refrigerate up to 5 days.",
  }),
  R({
    id: "sg-b3", title: "Chunky Monkey Zucchini Banana Muffins",
    category: "Breakfast", mealType: "Breakfast", prepTime: 10, cookTime: 25, servings: 12,
    source: "Ambitious Kitchen", sourceUrl: "https://www.ambitiouskitchen.com/chunky-monkey-zucchini-banana-muffins/",
    image: "https://www.ambitiouskitchen.com/wp-content/uploads/2023/04/Chunky-Monkey-Banana-Zucchini-Muffins-7-594x594.jpg",
    tags: ["Healthy", "Kid Friendly", "Meal Prep"],
    notes: "Hidden veggie (zucchini). Serving = 1 muffin. Freeze up to 3 months; microwave ~1 min to reheat. Sweetened mostly with banana.",
    macros: { calories: 207, protein: 3.1, carbs: 29.1, fat: 9.9, fiber: 4, sugar: 12.7, sodium: 150 },
    ingredients: [
      ing("1 1/2 cups whole wheat pastry or white whole wheat flour"), ing("1 tsp baking soda"),
      ing("1/2 tsp cinnamon"), ing("1/4 tsp salt"),
      ing("3/4 cup mashed ripe banana (about 2 small-medium)"), ing("2 tbsp olive or melted coconut oil"),
      ing("1/4 cup honey or pure maple syrup"), ing("2 tsp vanilla extract"), ing("1 egg"),
      ing("1 heaping cup shredded zucchini, squeezed dry"), ing("1/3 cup unsweetened vanilla almond milk"),
      ing("1/2 cup chocolate chips"), ing("1/3 cup chopped toasted walnuts"),
      ing("1/3 cup fine shredded unsweetened coconut"),
    ],
    instructions: "1. Preheat oven to 350°F. Line a 12-cup muffin tin and spray with nonstick spray.\n2. Whisk flour, baking soda, cinnamon and salt.\n3. In a separate bowl combine banana, oil, honey, egg, vanilla, zucchini and almond milk.\n4. Stir dry into wet until just combined. Fold in chocolate chips, walnuts and coconut.\n5. Divide among liners. Bake 22-27 min until a toothpick comes out clean.\n6. Cool in tin 5-10 min, then transfer to a rack.",
  }),
  R({
    id: "sg-b4", title: "Healthy Banana Zucchini Muffins",
    category: "Breakfast", mealType: "Breakfast", prepTime: 10, cookTime: 22, servings: 12,
    source: "iFoodReal", sourceUrl: "https://ifoodreal.com/banana-zucchini-muffins/",
    image: "https://ifoodreal.com/wp-content/uploads/2021/06/fg-Banana-Zucchini-Muffins-300x300.jpg",
    tags: ["Healthy", "Kid Friendly", "Meal Prep"],
    notes: "Hidden veggie (zucchini). Serving = 1 muffin. Freezer up to 3 months. Naturally sweetened with banana + a little maple.",
    macros: { calories: 185, protein: 4, carbs: 26, fat: 8, fiber: 3, sugar: 10, sodium: 139 },
    ingredients: [
      ing("2 large very ripe bananas, mashed (1 cup)"), ing("1 cup grated zucchini, squeezed dry"),
      ing("1 large egg"), ing("1/3 cup maple syrup or honey"), ing("3 tbsp avocado or olive oil"),
      ing("1 tsp pure vanilla extract"), ing("1 tsp baking powder"), ing("1/2 tsp baking soda"),
      ing("1/4 tsp salt"), ing("1 1/2 cups whole wheat flour"), ing("3.5 oz dark chocolate bar, chopped"),
    ],
    instructions: "1. Preheat oven to 375°F. Line a 12-cup muffin tin and spray.\n2. Mash bananas; add zucchini, egg, maple, oil, vanilla, baking powder, baking soda and salt. Whisk.\n3. Add flour and gently stir until just incorporated.\n4. Fold in chocolate chunks.\n5. Fill cups almost full; bake 21-22 min until a toothpick comes out clean.\n6. Cool in tin 5 min, then transfer to a rack.",
  }),
  R({
    id: "sg-b5", title: "Cottage Cheese Egg Bake",
    category: "Breakfast", mealType: "Breakfast", prepTime: 10, cookTime: 30, servings: 4,
    source: "The Real Food Dietitians", sourceUrl: "https://therealfooddietitians.com/cottage-cheese-egg-bake/",
    image: "https://therealfooddietitians.com/wp-content/uploads/2025/06/cottage-cheese-egg-bake-5.jpg",
    tags: ["Healthy", "Meal Prep"],
    notes: "High protein, low carb, one-dish. Hidden spinach. Fridge up to 3 days; slices freeze and reheat well.",
    macros: { calories: 248, protein: 21, carbs: 7, fat: 15, fiber: 1, sugar: 4, sodium: 787 },
    ingredients: [
      ing("Nonstick cooking spray"), ing("8 eggs"), ing("1/4 tsp garlic powder"),
      ing("1/4 tsp fine salt"), ing("1/4 tsp black pepper"),
      ing("3/4 cup 2% or full-fat cottage cheese"), ing("1/2 cup shredded/shaved Parmesan"),
      ing("3 cups roughly chopped fresh spinach"), ing("1/2 cup finely diced yellow or green onion"),
    ],
    instructions: "1. Preheat oven to 375°F. Coat a 9x9 baking dish with nonstick spray.\n2. Whisk eggs, garlic powder, salt and pepper. Fold in cottage cheese, Parmesan, spinach and onion.\n3. Pour into the dish.\n4. Bake 30-35 min until the center is set.\n5. Refrigerate leftovers up to 3 days; reheat in a skillet or microwave.",
  }),
  R({
    id: "sg-b6", title: "Banana Blueberry Baked Oatmeal Cups",
    category: "Breakfast", mealType: "Breakfast", prepTime: 10, cookTime: 25, servings: 12,
    source: "Two Peas & Their Pod", sourceUrl: "https://www.twopeasandtheirpod.com/banana-blueberry-baked-oatmeal-cups/",
    image: "https://www.twopeasandtheirpod.com/wp-content/uploads/2017/02/Banana-Blueberry-Baked-Oatmeal-Cups-3.jpg",
    tags: ["Healthy", "Kid Friendly", "Meal Prep"],
    notes: "Serving = 1 cup. Naturally sweetened. Freezer up to 1 month; microwave to reheat. Add a scoop of protein powder to boost protein.",
    macros: { calories: 103, protein: 2, carbs: 16, fat: 4, fiber: 2, sugar: 5, sodium: 126 },
    ingredients: [
      ing("1 tbsp ground flaxseed + 3 tbsp water"), ing("2 cups old fashioned oats"),
      ing("1 tsp baking powder"), ing("1/2 tsp sea salt"), ing("1 tsp ground cinnamon"),
      ing("1 large ripe banana, mashed (1/2 cup)"), ing("2 tbsp coconut oil, melted"),
      ing("1 cup unsweetened vanilla almond milk"), ing("2 tbsp pure maple syrup"),
      ing("1/2 tsp pure vanilla extract"), ing("1 cup blueberries, fresh or frozen"),
    ],
    instructions: "1. Preheat oven to 350°F. Grease a muffin pan.\n2. Combine flaxseed and water; let sit.\n3. Mix oats, baking powder, salt and cinnamon.\n4. In another bowl combine banana, flax mixture, coconut oil, almond milk, maple and vanilla.\n5. Add wet to dry and mix. Fold in blueberries. Divide into the pan.\n6. Bake 23-25 min until golden. Cool 5 min before removing.",
  }),
  R({
    id: "sg-b7", title: "Meal Prep Breakfast Burritos (Freezer Friendly)",
    category: "Breakfast", mealType: "Breakfast", prepTime: 35, cookTime: 25, servings: 10,
    source: "The Real Food Dietitians", sourceUrl: "https://therealfooddietitians.com/meal-prep-breakfast-burritos/",
    image: "https://therealfooddietitians.com/wp-content/uploads/2021/08/Meal-Prep-Breakfast-Burritos-22.jpg",
    tags: ["Meal Prep", "Family Favorite"],
    notes: "Serving = 1 burrito. Wrap in parchment + foil; freeze up to 3 months. Reheat in microwave. Use turkey sausage to keep it leaner.",
    macros: { calories: 530, protein: 21, carbs: 44, fat: 30, fiber: 4, sugar: 3, sodium: 987 },
    ingredients: [
      ing("1 lb frozen tater tots (~3 cups)"), ing("1 lb ground turkey or pork breakfast sausage"),
      ing("2 tsp olive oil"), ing("1 diced bell pepper (~1 cup)"),
      ing("1/2 small yellow onion, finely diced (~1/2 cup)"), ing("12 large eggs"),
      ing("1 cup shredded cheddar cheese"), ing("10 (10-inch) flour tortillas"),
    ],
    instructions: "1. Bake tater tots per package (40 tots total, 4 per burrito).\n2. Cook sausage in a skillet, crumbling, ~7 min; drain.\n3. Sauté bell pepper and onion in olive oil ~6 min until tender.\n4. Whisk eggs; pour into the veg and cook until set, 3-5 min.\n5. Fold in cooked sausage. Cool ~10 min.\n6. Warm tortillas. Scoop ~1 cup filling onto each, add 4 tots and 1-2 tbsp cheese; roll.\n7. Wrap each in parchment then foil. Label and freeze up to 3 months.",
  }),
  R({
    id: "sg-b8", title: "Apple Carrot Oatmeal Muffins",
    category: "Breakfast", mealType: "Breakfast", prepTime: 25, cookTime: 20, servings: 12,
    source: "Well Plated", sourceUrl: "https://www.wellplated.com/apple-carrot-muffins/",
    image: "https://www.wellplated.com/wp-content/uploads/2018/10/Healthy-Apple-Carrot-Oatmeal-Muffins.jpg",
    tags: ["Healthy", "Kid Friendly", "Meal Prep"],
    notes: "Hidden veggie (carrot) + apple. Serving = 1 muffin. Skip the optional glaze to cut sugar (macros below include glaze). Freezer up to 3 months.",
    macros: { calories: 226, protein: 5, carbs: 34, fat: 8, fiber: 3, sugar: 20, sodium: 180 },
    ingredients: [
      ing("1/2 cup golden raisins, walnuts or pecans (mix-ins of choice)"), ing("1/4 cup coconut oil"),
      ing("1 1/4 cups white whole wheat flour"), ing("1 cup old fashioned rolled oats"),
      ing("1 1/2 tsp baking powder"), ing("1/2 tsp baking soda"), ing("1 tsp ground cinnamon"),
      ing("1/4 tsp ground ginger"), ing("1/4 tsp kosher salt"),
      ing("3/4 cup grated carrot (about 1 large)"), ing("3/4 cup grated apple (1 small)"),
      ing("2 large eggs, room temp"), ing("1/2 cup plain nonfat Greek yogurt"),
      ing("1/3 cup honey or maple syrup"), ing("2 tsp pure vanilla extract"),
      ing("Optional glaze: 3/4 cup powdered sugar + 1 tbsp honey + 1/2 tbsp milk"),
    ],
    instructions: "1. Preheat oven to 350°F. Line 12 muffin cups. Toast nuts 8-12 min, then chop.\n2. Melt coconut oil; cool to room temp.\n3. Whisk flour, oats, baking powder, baking soda, cinnamon, ginger and salt. Fold in carrot and apple.\n4. Whisk eggs, yogurt, honey and vanilla into the oil. Combine wet and dry until just mixed. Fold in nuts.\n5. Divide among cups. Bake 18-22 min until a toothpick comes out clean. Cool 4 min, then move to a rack.\n6. Optional: whisk glaze and drizzle over cooled muffins.",
  }),
  R({
    id: "sg-b9", title: "Gluten-Free Freezer Protein Waffles",
    category: "Breakfast", mealType: "Breakfast", prepTime: 10, cookTime: 20, servings: 4,
    source: "Fit Mama Real Food", sourceUrl: "https://www.fitmamarealfood.com/protein-waffles/",
    image: "https://www.fitmamarealfood.com/wp-content/uploads/2020/01/Gluten-free-freezer-protein-waffles-made-in-the-blender.jpg",
    tags: ["Healthy", "Meal Prep", "Kid Friendly"],
    notes: "Blender batter. Protein from cottage cheese + eggs (no protein powder). Freeze in a single layer up to 6 months; toast to reheat.",
    macros: { calories: 329, protein: 24, carbs: 27, fat: 14, fiber: 4, sugar: 4, sodium: 759 },
    ingredients: [
      ing("6 eggs"), ing("2 cups cottage cheese"), ing("1 cup almond milk (unsweetened plain)"),
      ing("2 tbsp melted butter or coconut oil"), ing("1 tsp pure vanilla extract"),
      ing("1.5 cups rolled oats"), ing("1 tbsp cinnamon"), ing("1 tsp baking powder"),
      ing("1/4 tsp sea salt"), ing("Coconut oil (optional, for the iron)"),
    ],
    instructions: "1. Add all ingredients to a blender and blend until smooth. Let batter sit at least 10 min (or overnight).\n2. Heat a waffle iron, add a touch of oil, and pour in batter.\n3. Cook until the waffle maker indicates done. Repeat with remaining batter.\n4. Cool, then freeze in a single layer; reheat in a toaster.",
  }),
  R({
    id: "sg-b10", title: "Sweet Potato Egg Cups",
    category: "Breakfast", mealType: "Breakfast", prepTime: 10, cookTime: 28, servings: 12,
    source: "A Paige of Positivity", sourceUrl: "https://apaigeofpositivity.com/sweet-potato-egg-cups/",
    image: "https://apaigeofpositivity.com/wp-content/uploads/2022/10/Sweet-Potato-Egg-Cups-16.jpg",
    tags: ["Healthy", "Meal Prep"],
    notes: "Serving = 1 cup. Hidden sweet potato + peppers. Fridge up to 5 days; freeze in a zip bag and reheat a few at a time.",
    macros: { calories: 99, protein: 7, carbs: 6, fat: 5, fiber: 1, sugar: 2, sodium: 317 },
    ingredients: [
      ing("1 medium sweet potato, grated"), ing("6 large eggs"),
      ing("1/2 cup + 2 tbsp liquid egg whites"), ing("3/4 cup small curd 1% cottage cheese"),
      ing("1/3 cup white onion, diced"), ing("1/2 medium bell pepper"), ing("1 tbsp Dijon mustard"),
      ing("1/4 cup shredded pepper jack cheese"), ing("1 tbsp Green Goddess seasoning"), ing("Cooking spray"),
    ],
    instructions: "1. Preheat oven to 350°F. Grate the sweet potato; finely dice onion and bell pepper.\n2. Blend eggs, egg whites, Dijon and cottage cheese 20-30 sec.\n3. Pour into a bowl; fold in sweet potato, onion, peppers and seasoning.\n4. Grease a 12-count muffin tin; fill each cup just under the top.\n5. Top with pepper jack.\n6. Bake 25-30 min until set in the center.",
  }),

  // ================================ LUNCH ================================
  R({
    id: "sg-l1", title: "Easy Turkey Chili",
    category: "Soup", mealType: "Lunch", prepTime: 15, cookTime: 35, servings: 8,
    source: "Iowa Girl Eats", sourceUrl: "https://iowagirleats.com/easy-turkey-chili/",
    image: "https://iowagirleats.com/wp-content/uploads/2025/02/Turkey-Chili-iowagirleats-Vertical.jpg",
    tags: ["Healthy", "Meal Prep", "Comfort Food"],
    notes: "One-pot. Freezes flat in gallon bags up to 3 months. High fiber. Use ground turkey breast for the leanest macros.",
    macros: { calories: 217, protein: 21, carbs: 26, fat: 4, fiber: 9, sugar: 5, sodium: 1000 },
    ingredients: [
      ing("1 tbsp extra virgin olive oil"), ing("1 red bell pepper, chopped"),
      ing("1 shallot or small yellow onion, chopped"), ing("1-2 jalapeños, seeded and minced"),
      ing("Salt and pepper to taste"), ing("3 cloves garlic, minced"), ing("1 lb ground turkey"),
      ing("15 oz can black beans, drained and rinsed"), ing("15 oz can pinto beans, drained and rinsed"),
      ing("15 oz can fire-roasted diced tomatoes"), ing("15 oz can tomato sauce"),
      ing("4 oz can diced green chiles"), ing("1/2 cup chicken broth"),
      ing("2 tbsp chili powder"), ing("1 tsp cumin"), ing("1 tsp onion powder"),
      ing("1 tsp paprika"), ing("1/2 tsp garlic powder"), ing("1/2 tsp dried oregano"), ing("1/2 tsp salt"),
    ],
    instructions: "1. Combine the chili seasoning in a small bowl; set aside.\n2. Heat oil in a Dutch oven over medium-high. Sauté pepper, shallot and jalapeño 5-7 min. Add garlic, 1 min.\n3. Add ground turkey; cook through, breaking it up.\n4. Add both beans, tomatoes, tomato sauce, green chiles, broth and seasoning; stir.\n5. Bring to a simmer, cover, reduce heat, simmer 20 min, stirring halfway.\n6. Serve with desired toppings.",
  }),
  R({
    id: "sg-l2", title: "Chicken Burrito Bowl (High Protein)",
    category: "Chicken", mealType: "Lunch", prepTime: 20, cookTime: 25, servings: 5,
    source: "Eat the Gains", sourceUrl: "https://eatthegains.com/chicken-burrito-bowls/",
    image: "https://eatthegains.com/wp-content/uploads/2019/09/Chicken-Burrito-Bowl-15-500x500.jpg",
    tags: ["Healthy", "Meal Prep", "Family Favorite"],
    notes: "Meal-prep bowls; components freeze (without guacamole) up to 3 months. Big protein + fiber. Cut rice to lower carbs.",
    macros: { calories: 621, protein: 40, carbs: 65, fat: 23, fiber: 12, sugar: 9, sodium: 832 },
    ingredients: [
      ing("1 1/2 lb chicken thighs"), ing("1 tbsp olive oil"), ing("1 lime, juiced"),
      ing("2 tbsp taco seasoning"), ing("1/3 cup cilantro, chopped"), ing("3 cloves garlic, minced"),
      ing("Salt and pepper to taste"), ing("1 cup jasmine rice, rinsed"), ing("1 cup water"),
      ing("2 small avocados"), ing("5 cups chopped romaine"),
      ing("1 (15 oz) can black beans, drained"), ing("1 cup pico de gallo"),
      ing("1 cup canned corn, drained"), ing("1 cup shredded Monterey Jack cheese"),
      ing("1/2 large onion + 3 bell peppers (fajita veggies)"),
    ],
    instructions: "1. Marinate chicken in olive oil, lime, cilantro, garlic, taco seasoning, salt and pepper 1-2 hrs.\n2. Cook rice; stir in cilantro, lime and salt.\n3. Sear chicken in a skillet ~10 min, flip, cook 5-10 min more. Rest, then slice.\n4. Sauté onions 4-5 min, add peppers, cover and cook 7-10 min.\n5. Mash avocados with lime, cilantro, salt and pepper.\n6. Divide rice, lettuce, beans, corn, chicken, pico, guac and cheese among bowls.",
  }),
  R({
    id: "sg-l3", title: "Ground Turkey Egg Roll in a Bowl",
    category: "Chicken", mealType: "Lunch", prepTime: 5, cookTime: 11, servings: 6,
    source: "iFoodReal", sourceUrl: "https://ifoodreal.com/turkey-egg-roll-in-a-bowl/",
    image: "https://ifoodreal.com/wp-content/uploads/2024/01/turkey-egg-roll-in-a-bowl.jpg",
    tags: ["Healthy", "Quick Weeknight", "Meal Prep"],
    notes: "One-pan, 15 min. Low calorie / high protein. Fridge 3-4 days; freezes. Skip the brown sugar to cut sugar further.",
    macros: { calories: 176, protein: 21, carbs: 11, fat: 6, fiber: 3, sugar: 6, sodium: 607 },
    ingredients: [
      ing("1 lb extra lean ground turkey"), ing("1 medium onion, finely chopped"),
      ing("3 large garlic cloves, minced"), ing("2 tbsp oil, divided"),
      ing("21 oz coleslaw mix (1.5 bags)"), ing("1 tbsp brown sugar"), ing("1/4 cup soy sauce"),
      ing("1 tbsp rice vinegar"), ing("1/3 cup green onion, chopped"),
    ],
    instructions: "1. Heat a large skillet on medium with 1 tbsp oil. Add onion, garlic and turkey; sauté 5 min, breaking it up.\n2. Add coleslaw; stir and cook 1-2 min.\n3. Sprinkle brown sugar and drizzle soy sauce and rice vinegar; stir-fry 2-3 min.\n4. Turn off heat, garnish with green onion and serve.",
  }),
  R({
    id: "sg-l4", title: "Baked Turkey Zucchini Meatballs",
    category: "Chicken", mealType: "Lunch", prepTime: 10, cookTime: 20, servings: 6,
    source: "The Natural Nurturer", sourceUrl: "https://thenaturalnurturer.com/oven-baked-turkey-zucchini-meatballs/",
    image: "https://thenaturalnurturer.com/wp-content/uploads/2021/10/turkey-zucchini-meatballs-1-of-1.jpg",
    tags: ["Healthy", "Kid Friendly", "Meal Prep"],
    notes: "Serving = 4 meatballs. Hidden zucchini keeps them moist. Freeze up to 3 months; reheat from frozen 3-4 min.",
    macros: { calories: 159, protein: 23, carbs: 6, fat: 5, fiber: 1, sugar: 1, sodium: 410 },
    ingredients: [
      ing("1 1/2 cup grated zucchini"), ing("1 lb ground turkey"),
      ing("1/2 cup panko breadcrumbs"), ing("1/2 tsp onion powder"), ing("1/2 tbsp Italian seasoning"),
      ing("1/2 tsp kosher salt"), ing("1/2 tsp garlic powder"), ing("1/4 tsp paprika"),
      ing("1/2 cup grated Parmesan cheese"), ing("1 large egg"),
    ],
    instructions: "1. Preheat oven to 400°F.\n2. Wrap shredded zucchini in a towel and squeeze out moisture.\n3. Combine zucchini and all remaining ingredients; mix well.\n4. Roll into golf ball-sized meatballs on a baking sheet.\n5. Bake 18-20 min until cooked through.\n6. Cool before storing (fridge 3-4 days).",
  }),
  R({
    id: "sg-l5", title: "Ground Turkey Sweet Potato Skillet (One Pan)",
    category: "Chicken", mealType: "Lunch", prepTime: 5, cookTime: 35, servings: 4,
    source: "Eat the Gains", sourceUrl: "https://eatthegains.com/ground-turkey-sweet-potato-skillet/",
    image: "https://eatthegains.com/wp-content/uploads/2022/02/Ground-Turkey-Sweet-Potato-Skillet-7-500x500.jpg",
    tags: ["Healthy", "Meal Prep", "Quick Weeknight"],
    notes: "One-pan. Hidden kale + peppers. Fridge up to 5 days; add cheese fresh when reheating. Freezes.",
    macros: { calories: 417, protein: 33, carbs: 45, fat: 13, fiber: 8.6, sugar: 11.8, sodium: 303 },
    ingredients: [
      ing("2 tbsp olive oil, divided"), ing("1 lb ground turkey"),
      ing("6 cups diced sweet potatoes (~2-3 small)"), ing("1 cup diced onion"),
      ing("2 tbsp water"), ing("2 heaping cups diced bell peppers"),
      ing("3 cups packed chopped kale"), ing("1/2 tbsp chili powder"), ing("1/2 tbsp cumin"),
      ing("1 tsp paprika"), ing("1 tsp garlic powder"),
      ing("3/4 cup shredded pepper jack cheese"), ing("Salt and pepper to taste"),
    ],
    instructions: "1. Heat a 12-inch skillet with 1 tbsp oil. Brown turkey with salt and pepper 5-7 min; set aside.\n2. Add remaining oil, sweet potatoes, onion, salt and pepper plus 2 tbsp water; cover and cook 12-15 min. Add peppers, cover, 5 min. Add kale + seasonings, 1-2 min.\n3. Return turkey with juices and spices; stir.\n4. Top with cheese, cover 1-2 min to melt. Serve.",
  }),
  R({
    id: "sg-l6", title: "Salmon Patties (Canned Salmon)",
    category: "Seafood", mealType: "Lunch", prepTime: 10, cookTime: 30, servings: 14,
    source: "Natasha's Kitchen", sourceUrl: "https://natashaskitchen.com/salmon-patties/",
    image: "https://natashaskitchen.com/wp-content/uploads/2017/06/Salmon-Cakes-4.jpg",
    tags: ["Healthy", "Meal Prep", "Quick Weeknight"],
    notes: "Serving = 1 patty. Omega-3s from canned salmon. Freeze cooked patties up to 2 months; thaw overnight, then reheat.",
    macros: { calories: 94, protein: 7, carbs: 3, fat: 6, fiber: 0.4, sugar: 1, sodium: 314 },
    ingredients: [
      ing("14-15 oz canned salmon, well drained"), ing("2 tbsp olive oil, divided"),
      ing("2 tbsp unsalted butter, divided"), ing("1 medium yellow onion, finely diced"),
      ing("1/2 red bell pepper, diced"), ing("1/2 cup panko bread crumbs"),
      ing("1 large egg, lightly beaten"), ing("2 tbsp mayonnaise"), ing("1 tsp Worcestershire sauce"),
      ing("1 tsp garlic salt"), ing("1/4 tsp black pepper"), ing("1/4 cup parsley, minced"),
    ],
    instructions: "1. Sauté onion and bell pepper in oil and butter over medium 7-9 min; remove from heat.\n2. Combine salmon, sautéed veg, panko, egg, mayo, Worcestershire, garlic salt, pepper and parsley. Form into 2-inch patties ~1/3 inch thick.\n3. Heat oil and butter in a skillet; sauté patties 3-4 min per side until golden. Drain on paper towels.",
  }),
  R({
    id: "sg-l7", title: "Crockpot White Chicken Chili (High Protein)",
    category: "Soup", mealType: "Lunch", prepTime: 15, cookTime: 240, servings: 8,
    source: "Lauren Fit Foodie", sourceUrl: "https://laurenfitfoodie.com/crockpot-white-chicken-chili/",
    image: "https://laurenfitfoodie.com/wp-content/uploads/2023/07/Crockpotwhitechickenchili-10-683x1024.jpg",
    tags: ["Healthy", "Meal Prep", "Comfort Food"],
    notes: "Dump-and-go crockpot. Freezes up to 3 months. Sodium not published by source (est.). ~36 g protein per bowl.",
    macros: { calories: 328, protein: 36, carbs: 27, fat: 8, fiber: 6, sugar: 6.5, sodium: 700 },
    ingredients: [
      ing("1 tbsp olive oil"), ing("1 small yellow onion, finely diced"),
      ing("2 lb boneless skinless chicken breast"), ing("2 (15 oz) cans white beans, rinsed"),
      ing("2 (4 oz) cans diced green chiles"), ing("1 jalapeño, seeded and diced"),
      ing("2.5 cups chicken stock"), ing("5 cloves garlic, minced"), ing("1 tbsp Italian seasoning"),
      ing("1 tbsp ground cumin"), ing("1.5 tsp salt"), ing("1.5 tsp paprika"),
      ing("1.25 cups frozen corn"), ing("4 oz reduced-fat cream cheese, softened"),
      ing("1/2 cup chopped fresh cilantro"),
    ],
    instructions: "1. Add all ingredients except cream cheese and cilantro to the crockpot; toss.\n2. Cover and cook low 5-6 hrs or high 3-4 hrs.\n3. Remove chicken. Immersion-blend ~1/3 of the chili to thicken.\n4. Shred chicken and return it.\n5. Stir in cream cheese and cilantro until melted.\n6. Serve with toppings.",
  }),
  R({
    id: "sg-l8", title: "High Protein Lentil Soup",
    category: "Soup", mealType: "Lunch", prepTime: 15, cookTime: 25, servings: 6,
    source: "Nourished by Nic", sourceUrl: "https://nourishedbynic.com/the-ultimate-cozy-high-protein-lentil-soup/",
    image: "https://nourishedbynic.com/wp-content/uploads/2022/11/High-Protein-Lentil-Soup-14-1.jpg",
    tags: ["Healthy", "Meal Prep", "Comfort Food"],
    notes: "Serving = 2 cups. One-pot. 16 g fiber. Freeze in portions up to 3 months. Hidden carrot/celery + greens.",
    macros: { calories: 259, protein: 18, carbs: 34, fat: 6, fiber: 16, sugar: 4, sodium: 196 },
    ingredients: [
      ing("2 tbsp olive oil"), ing("1 medium yellow onion, diced"), ing("2 celery stalks, diced"),
      ing("2 carrots, diced"), ing("4 garlic cloves, pressed"), ing("1.5 cups dry red lentils"),
      ing("4 cups chicken bone broth"), ing("1 tsp ground cumin"), ing("1/2 cup low-sodium tomato sauce"),
      ing("1 cup water"), ing("3 cups chopped kale or spinach"), ing("Salt and black pepper to taste"),
    ],
    instructions: "1. Heat olive oil over medium. Sauté onion, carrots and celery ~5 min. Add garlic, 1 min.\n2. Add broth, lentils and cumin. Cover, lower heat and simmer ~25 min.\n3. Add tomato sauce, water and greens. Season with salt and pepper.",
  }),
  R({
    id: "sg-l9", title: "Baked Buffalo Chicken Meatballs",
    category: "Chicken", mealType: "Lunch", prepTime: 15, cookTime: 20, servings: 26,
    source: "Skinnytaste", sourceUrl: "https://www.skinnytaste.com/buffalo-chicken-meatballs/",
    image: "https://www.skinnytaste.com/wp-content/uploads/2015/01/SkinnyChickenBuffaloMeatballs.jpg",
    tags: ["Healthy", "Meal Prep"],
    notes: "Serving = 1 meatball (recipe makes 26). Hidden carrot + celery. Baked, not fried. Freeze up to 3 months.",
    macros: { calories: 37, protein: 4, carbs: 1, fat: 2, fiber: 0, sugar: 0, sodium: 135 },
    ingredients: [
      ing("Oil spray"), ing("1 1/4 lb 93% lean ground chicken"), ing("1/4 cup panko crumbs"),
      ing("1 large egg"), ing("2 scallions, chopped"), ing("1/3 cup finely minced celery"),
      ing("1/3 cup finely minced carrot"), ing("1 clove crushed garlic"),
      ing("Kosher salt and black pepper to taste"), ing("1/3 cup Frank's hot sauce"),
      ing("1/4 cup blue cheese dressing (optional)"),
    ],
    instructions: "1. Preheat oven to 400°F. Spray a nonstick baking sheet.\n2. Combine chicken, panko, egg, scallions, celery, carrot and garlic; season.\n3. Roll into 26 meatballs (~1/8 cup each).\n4. Bake 16-18 min until cooked through and golden.\n5. Toss meatballs with buffalo sauce.\n6. Serve with blue cheese dressing if desired.",
  }),
  R({
    id: "sg-l10", title: "Teriyaki Chicken Meal Prep Bowls",
    category: "Chicken", mealType: "Lunch", prepTime: 15, cookTime: 20, servings: 4,
    source: "Healthy Fitness Meals", sourceUrl: "https://healthyfitnessmeals.com/teriyaki-chicken-meal-prep-bowls-recipe/",
    image: "https://healthyfitnessmeals.com/wp-content/uploads/2019/02/Teriyaki-chicken-bowls-6.jpg",
    tags: ["Healthy", "Meal Prep", "Family Favorite"],
    notes: "One-pan chicken, homemade lighter teriyaki (honey, not sugar). Fridge 3-5 days; freeze up to 3 months. 42 g protein.",
    macros: { calories: 422, protein: 42, carbs: 39, fat: 10, fiber: 4, sugar: 7, sodium: 762 },
    ingredients: [
      ing("1.5 lb boneless skinless chicken breast or thighs, cubed"), ing("1 tbsp sesame oil"),
      ing("4 cups broccoli florets"), ing("2 cups cooked brown rice or quinoa"),
      ing("1 tbsp sesame seeds"), ing("2 tbsp sliced green onions"),
      ing("2 garlic cloves, grated"), ing("2 tbsp fresh ginger, grated"), ing("1 tbsp raw honey"),
      ing("1/4 cup low-sodium soy sauce"), ing("1/4 cup fresh orange juice"), ing("1/2 tbsp cornstarch"),
    ],
    instructions: "1. Heat sesame oil over medium-high. Cook chicken 4-5 min until almost done.\n2. Whisk garlic, ginger, honey, soy sauce, orange juice and cornstarch; pour over chicken.\n3. Simmer 3-5 min until the sauce thickens.\n4. Steam broccoli 5-8 min.\n5. Divide rice among 4 containers; top with broccoli and chicken.\n6. Garnish with sesame seeds and green onion. Refrigerate 3-5 days.",
  }),

  // =============================== DINNER ===============================
  R({
    id: "sg-d1", title: "Sheet Pan Chicken Fajitas",
    category: "Chicken", mealType: "Dinner", prepTime: 20, cookTime: 18, servings: 6,
    source: "The Real Food Dietitians", sourceUrl: "https://therealfooddietitians.com/sheet-pan-chicken-fajitas/",
    image: "https://therealfooddietitians.com/wp-content/uploads/2019/01/Sheet-Pan-Chicken-Fajitas-018.jpg",
    tags: ["Healthy", "Quick Weeknight", "Family Favorite"],
    notes: "One-pan / dump. Freezer meal: bag raw seasoned chicken + veggies up to 3 months, thaw and bake. Serving = ~1 cup + 2 tortillas.",
    macros: { calories: 395, protein: 26, carbs: 35, fat: 9, fiber: 4, sugar: 5, sodium: 840 },
    ingredients: [
      ing("2 tsp chili powder"), ing("2 tsp ground cumin"), ing("1 1/2 tsp garlic powder"),
      ing("1 tsp paprika"), ing("1 tsp dried oregano"), ing("1 tsp fine salt"), ing("1/2 tsp black pepper"),
      ing("1-1 1/2 lb boneless skinless chicken breast, cut into strips"),
      ing("3 bell peppers, cut into strips"), ing("1 medium sweet onion, sliced"),
      ing("1 tbsp avocado oil"), ing("12-16 small flour or corn tortillas"),
    ],
    instructions: "1. Place a large sheet pan on the middle rack; preheat oven to 425°F.\n2. Combine seasoning spices.\n3. Toss chicken, peppers and onion with oil and seasoning.\n4. Remove the hot pan, mist with spray, spread ingredients evenly.\n5. Bake 14-16 min until chicken is cooked.\n6. Warm tortillas in foil the last 5 min.\n7. Serve with toppings.",
  }),
  R({
    id: "sg-d2", title: "Chicken Enchilada Casserole",
    category: "Chicken", mealType: "Dinner", prepTime: 15, cookTime: 35, servings: 8,
    source: "Healthy Fitness Meals", sourceUrl: "https://healthyfitnessmeals.com/chicken-enchilada-casserole/",
    image: "https://healthyfitnessmeals.com/wp-content/uploads/2022/11/FHFM-chicken-enchilada-casserole.jpg",
    tags: ["Healthy", "Meal Prep", "Family Favorite"],
    notes: "Dump-and-bake layered casserole. Assemble and freeze up to 3 months, thaw overnight, then bake.",
    macros: { calories: 283, protein: 20, carbs: 20, fat: 13, fiber: 3, sugar: 4, sodium: 754 },
    ingredients: [
      ing("10 small corn tortillas, cut in half"), ing("2 1/2 cups shredded cooked chicken"),
      ing("2 cups shredded cheddar cheese, divided"), ing("2 cups red enchilada sauce"),
      ing("1 (15 oz) can black beans, rinsed"), ing("1 (15 oz) can corn, drained"),
      ing("1 (14.5 oz) can roasted red pepper, chopped"),
    ],
    instructions: "1. Preheat oven to 350°F; spray a baking dish.\n2. Mix chicken with 1 cup cheese and enchilada sauce.\n3. Layer tortillas, one-third of the meat mixture, then beans, corn and peppers. Repeat.\n4. Top with the remaining cup of cheese.\n5. Cover with foil; bake 30 min. Uncover and bake 5-10 min until golden.\n6. Garnish and serve.",
  }),
  R({
    id: "sg-d3", title: "Turkey Meatloaf Muffins (with Sneaky Veggies)",
    category: "Chicken", mealType: "Dinner", prepTime: 10, cookTime: 25, servings: 12,
    source: "Thriving Home", sourceUrl: "https://thrivinghomeblog.com/mini-turkey-and-veggie-meatloaves/",
    image: "https://thrivinghomeblog.com/wp-content/uploads/2016/07/Turkey-Meatloaf-Muffins.jpg",
    tags: ["Healthy", "Kid Friendly", "Meal Prep"],
    notes: "Serving = 1 muffin. Hidden carrot, zucchini and onion. Freeze up to 3 months; reheat. Use all-natural ketchup to keep sugar down.",
    macros: { calories: 123, protein: 16, carbs: 9, fat: 3, fiber: 1, sugar: 4, sodium: 372 },
    ingredients: [
      ing("1/2 cup carrot, shredded"), ing("1/2 cup zucchini, shredded and squeezed dry"),
      ing("1/2 cup onion, shredded and squeezed dry"), ing("2 tbsp fresh parsley, minced"),
      ing("1 1/2 lb lean ground turkey"), ing("3/4 cup panko bread crumbs"),
      ing("1/2 cup grated Parmesan cheese"), ing("1 large egg, beaten"),
      ing("3/4 cup ketchup, divided"), ing("1/2 tsp salt"), ing("1/2 tsp pepper"), ing("3/4 tsp garlic powder"),
    ],
    instructions: "1. Preheat oven to 450°F. Spray a muffin tin generously.\n2. Combine shredded veggies, parsley, turkey, bread crumbs, Parmesan, egg, 1/4 cup ketchup, salt, pepper and garlic powder. Don't over-mix.\n3. Scoop 1/3 cup into each cup; press evenly. Top each with 1-2 tsp ketchup.\n4. Bake 20-25 min until 165°F.\n5. Broil ~2 min to caramelize the top, watching closely.",
  }),
  R({
    id: "sg-d4", title: "High Protein Baked Ziti with Cottage Cheese",
    category: "Pasta", mealType: "Dinner", prepTime: 10, cookTime: 40, servings: 8,
    source: "iFoodReal", sourceUrl: "https://ifoodreal.com/high-protein-baked-ziti/",
    image: "https://ifoodreal.com/wp-content/uploads/2025/08/high-protein-baked-ziti-fg.jpg",
    tags: ["Meal Prep", "Family Favorite", "Comfort Food"],
    notes: "Cottage cheese swaps in for ricotta to boost protein (40 g/serving). Freeze up to 3 months; bake ~1 hr from frozen.",
    macros: { calories: 544, protein: 40, carbs: 52, fat: 19, fiber: 3, sugar: 8, sodium: 710 },
    ingredients: [
      ing("16 oz ziti pasta"), ing("1 medium onion, finely chopped"),
      ing("1 lb ground turkey or extra lean ground beef"), ing("2 tsp oil"),
      ing("23 oz marinara sauce"), ing("16 oz cottage cheese"), ing("1 cup milk"),
      ing("2 1/2 cups shredded mozzarella cheese"), ing("1/2 cup grated Parmesan cheese"),
      ing("2 tbsp basil or parsley, chopped"), ing("Cooking spray"),
    ],
    instructions: "1. Preheat oven to 425°F; spray a 9x13 dish.\n2. Cook pasta until al dente; drain.\n3. Blend cottage cheese with milk until smooth.\n4. Sauté onion 3 min, add ground meat, cook 7 min.\n5. Stir in marinara, Parmesan and the blended cottage cheese.\n6. Combine sauce with pasta. Layer half the pasta + 1 cup mozzarella, then remaining pasta + 1 1/2 cups mozzarella.\n7. Bake uncovered 20 min until bubbly. Rest 5 min; garnish.",
  }),
  R({
    id: "sg-d5", title: "Turkey Stuffed Peppers",
    category: "Chicken", mealType: "Dinner", prepTime: 15, cookTime: 50, servings: 4,
    source: "Eating Bird Food", sourceUrl: "https://www.eatingbirdfood.com/turkey-stuffed-peppers/",
    image: "https://www.eatingbirdfood.com/wp-content/uploads/2026/02/turkey-stuffed-peppers-new-hero-300x300.jpg",
    tags: ["Healthy", "Meal Prep", "Family Favorite"],
    notes: "Serving = 2 pepper halves. Assemble (no cheese) and freeze up to 2 months; thaw and bake +5 min.",
    macros: { calories: 326, protein: 26, carbs: 24, fat: 14, fiber: 5, sugar: 7, sodium: 505 },
    ingredients: [
      ing("4 bell peppers, any color"), ing("1/2 tbsp olive or avocado oil"),
      ing("1/2 medium yellow onion, chopped"), ing("2 cloves garlic, minced"), ing("1 lb ground turkey"),
      ing("1 1/2 tbsp Italian seasoning"), ing("1/2 tsp sea salt"), ing("1/4 tsp ground pepper"),
      ing("1/4 tsp ground cinnamon"), ing("1 cup cooked brown rice"),
      ing("1 1/3 cup tomato sauce, divided"), ing("1/3 cup shredded mozzarella cheese"),
    ],
    instructions: "1. Preheat oven to 375°F. Halve peppers and remove seeds.\n2. Sauté onion and garlic 5-6 min. Add turkey; cook 7-8 min.\n3. Add seasoning, salt, pepper and cinnamon; 1 min.\n4. Off heat, mix in rice and 1 cup tomato sauce.\n5. Fill peppers in a 9x13 dish; top with sauce and cheese. Pour 1 cup water around them.\n6. Cover with foil; bake 35 min. Uncover, bake 5 min.",
  }),
  R({
    id: "sg-d6", title: "Healthy Turkey Shepherd's Pie",
    category: "Chicken", mealType: "Dinner", prepTime: 25, cookTime: 30, servings: 6,
    source: "The Clean Eating Couple", sourceUrl: "https://thecleaneatingcouple.com/turkey-shepherds-pie/",
    image: "https://thecleaneatingcouple.com/wp-content/uploads/2022/10/healthy-sheperds-pie-1-681x1024.jpg",
    tags: ["Healthy", "Meal Prep", "Comfort Food"],
    notes: "Hidden cauliflower in the mash + carrots/peas/corn. Assemble and freeze up to 3 months; bake from thawed.",
    macros: { calories: 256, protein: 25, carbs: 22, fat: 9, fiber: 4, sugar: 4, sodium: 386 },
    ingredients: [
      ing("1 1/2 cups russet potatoes, peeled and chopped"), ing("1 1/2 cups cauliflower florets"),
      ing("1/2 cup grated Parmesan cheese"), ing("1 tbsp olive oil (topping)"),
      ing("1/4 tsp garlic powder"), ing("1/2 cup chicken broth (topping)"),
      ing("1 tbsp olive oil (filling)"), ing("1 lb ground turkey"), ing("1 cup diced onion"),
      ing("1 tbsp minced garlic"), ing("1/2 cup diced carrots"), ing("1/2 tsp dried rosemary"),
      ing("1/2 tsp dried thyme"), ing("1/2 cup low sodium chicken stock"), ing("1 tbsp tomato paste"),
      ing("1 cup peas"), ing("1 cup corn"), ing("Salt and pepper to taste"),
    ],
    instructions: "1. Preheat oven to 350°F; grease an 8x8 dish.\n2. Boil potatoes and cauliflower ~10 min until soft; drain.\n3. Brown turkey 5 min; add onion, garlic and carrots, cook 5 min.\n4. Add seasonings, broth, tomato paste, peas and corn; stir.\n5. Mash potatoes and cauliflower with oil, garlic powder, salt, pepper, broth and Parmesan.\n6. Layer the turkey mixture, top with mash.\n7. Bake 30 min until golden.",
  }),
  R({
    id: "sg-d7", title: "Sheet Pan Salmon with Potatoes & Chickpeas",
    category: "Seafood", mealType: "Dinner", prepTime: 10, cookTime: 35, servings: 6,
    source: "Ambitious Kitchen", sourceUrl: "https://www.ambitiouskitchen.com/sheet-pan-salmon/",
    image: "https://www.ambitiouskitchen.com/wp-content/uploads/2025/03/Sheet-Pan-Salmon-with-Potatoes-and-Chickpeas-5-594x594.jpg",
    tags: ["Healthy", "Family Favorite"],
    notes: "One-pan / dump. ~40 g protein + omega-3s. Best fresh (salmon), but roasted potatoes/chickpeas reheat well. Sodium not published (est.).",
    macros: { calories: 526, protein: 40, carbs: 28, fat: 30, fiber: 5, sugar: 3, sodium: 480 },
    ingredients: [
      ing("1 lb baby potatoes"), ing("1 (15 oz) can chickpeas, rinsed and dried"),
      ing("1 red onion, halved and sliced"), ing("3 tbsp extra virgin olive oil, divided"),
      ing("1 1/2 tsp paprika"), ing("1 1/2 tsp cumin"), ing("1 1/2 tsp garlic powder"),
      ing("1 1/2 tsp kosher salt"), ing("1 tsp ground turmeric"), ing("1 tsp fresh thyme"),
      ing("30 oz salmon, cut into 4-6 filets"),
      ing("1 cup plain whole milk Greek yogurt (sauce)"), ing("1/2 cup fresh herbs (sauce)"),
      ing("1 garlic clove, grated (sauce)"), ing("1 tsp lemon juice (sauce)"),
      ing("2-4 oz feta cheese, to serve"),
    ],
    instructions: "1. Preheat oven to 400°F; line a baking sheet.\n2. Combine the spices.\n3. Toss potatoes, chickpeas and onion with 2 tbsp oil and 1 tbsp spice mix. Bake 20 min.\n4. Blend yogurt, herbs, garlic, lemon and salt for the sauce.\n5. Rub salmon with 1 tbsp oil and remaining spice.\n6. Push veg to edges, add salmon, bake 10-15 min.\n7. Drizzle with yogurt sauce, top with feta and herbs.",
  }),
  R({
    id: "sg-d8", title: "Unstuffed Cabbage Rolls",
    category: "Chicken", mealType: "Dinner", prepTime: 10, cookTime: 40, servings: 4,
    source: "Eating Bird Food", sourceUrl: "https://www.eatingbirdfood.com/unstuffed-cabbage-rolls/",
    image: "https://www.eatingbirdfood.com/wp-content/uploads/2020/06/unstuffed-cabbage-roll-2.jpg",
    tags: ["Healthy", "Meal Prep", "Comfort Food"],
    notes: "One-pot skillet. 29 g protein, 9 g fiber. Freezes well up to 3 months. Serve over cauliflower rice to keep carbs low.",
    macros: { calories: 291, protein: 29, carbs: 23, fat: 11, fiber: 9, sugar: 13, sodium: 575 },
    ingredients: [
      ing("2 tsp olive oil"), ing("1 lb ground turkey"), ing("4 cloves garlic, minced"),
      ing("1 yellow onion, chopped"), ing("1 tsp sea salt"), ing("1/2 tsp black pepper"),
      ing("4 tbsp apple cider vinegar"), ing("1/4 tsp cinnamon"), ing("1 (14 oz) can diced tomatoes"),
      ing("1 (8 oz) can tomato sauce"), ing("1/3 cup unsweetened applesauce"),
      ing("1/2 head (~7 cups) shredded green cabbage"), ing("Cauliflower rice or rice, to serve"),
    ],
    instructions: "1. Heat a Dutch oven over medium-high. Brown turkey, onion and garlic 5-7 min.\n2. Add cabbage, diced tomatoes, tomato sauce, vinegar, applesauce, cinnamon, salt and pepper. Bring to a boil.\n3. Cover, reduce heat and simmer ~30 min until cabbage is tender.\n4. Serve over cauliflower rice or rice; garnish with parsley.",
  }),
  R({
    id: "sg-d9", title: "Dump-and-Bake Chicken Broccoli Rice Casserole",
    category: "Chicken", mealType: "Dinner", prepTime: 10, cookTime: 60, servings: 4,
    source: "The Seasoned Mom", sourceUrl: "https://www.theseasonedmom.com/chicken-broccoli-rice-casserole-2/",
    image: "https://www.theseasonedmom.com/wp-content/uploads/2024/06/dump-and-bake-chicken-broccoli-rice-casserole-10.jpg",
    tags: ["Meal Prep", "Family Favorite", "Comfort Food"],
    notes: "True dump-and-bake — raw rice + chicken cook in the dish. Assemble unbaked and freeze up to 3 months; thaw and bake.",
    macros: { calories: 406, protein: 35, carbs: 47, fat: 6.3, fiber: 3.2, sugar: 2.7, sodium: 995 },
    ingredients: [
      ing("1 (10.5 oz) can condensed cream of chicken soup"), ing("2 cups chicken broth, water or milk"),
      ing("1 cup uncooked long grain white rice"),
      ing("1 lb boneless skinless chicken breast or thighs, diced"),
      ing("1 (12.6 oz) bag frozen baby broccoli florets"), ing("1 cup grated sharp cheddar cheese"),
      ing("Kosher salt and black pepper to taste"), ing("Optional herbs (garlic/onion powder, thyme)"),
    ],
    instructions: "1. Preheat oven to 375°F; spray a 9x13 dish. Whisk soup and broth.\n2. Stir in uncooked rice, raw diced chicken and frozen broccoli. Season.\n3. Cover tightly with foil; bake 55-60 min until liquid is absorbed and chicken is cooked.\n4. Sprinkle cheese on top; return briefly until melted.\n5. Garnish and serve.",
  }),
  R({
    id: "sg-d10", title: "Sheet Pan Sausage with Potatoes & Green Beans",
    category: "Pork", mealType: "Dinner", prepTime: 5, cookTime: 25, servings: 4,
    source: "The Whole Cook", sourceUrl: "https://thewholecook.com/sheet-pan-sausage-potatoes-green-beans/",
    image: "https://thewholecook.com/wp-content/uploads/2021/04/Sausage-with-Potatoes-Green-Beans-by-The-Whole-Cook-vertical-2-680x980.jpg",
    tags: ["Quick Weeknight", "Family Favorite", "Meal Prep"],
    notes: "One-pan / dump, 30 min. Use chicken or turkey sausage to lower fat/sodium. Leftovers reheat well; freezes.",
    macros: { calories: 358, protein: 18, carbs: 25, fat: 23, fiber: 5, sugar: 4, sodium: 1323 },
    ingredients: [
      ing("4 fully cooked sausages, sliced into 1/4-inch circles"), ing("12 oz fresh green beans, trimmed"),
      ing("1 lb potatoes, cut into 1-inch chunks"), ing("3 tbsp extra virgin olive oil"),
      ing("3/4 tsp salt"), ing("1/2 tsp pepper"), ing("1/2 tsp garlic powder"),
      ing("1/2 tsp dried basil"), ing("1/2 tsp dried oregano"),
    ],
    instructions: "1. Preheat oven to 425°F; line a baking sheet.\n2. Spread green beans, potatoes and sausage on the pan. Drizzle with oil and sprinkle seasonings; toss and spread in a single layer.\n3. Bake 20-25 min until potatoes are tender.",
  }),
];
